# Exclude a variety of commonly ignored directories.
exclude = [
    ".eggs",
    ".git",
    ".git-rewrite",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    ".vscode",
    "build",
    "dist",
    "docs",
    "resources",
    "tests/fixtures",
    "helmfile.d",
    ".make",
]
 
# Same as Black.
line-length = 88
indent-width = 4
 
[lint]
select = [
    "D", # pydocstyle
    "E", # pycodestyle-error
    "W", # pycodestyle-warning
    "F", # pyflakes
    "A", # flake8-builtins
    "PT", # flake8-pytest-style
    "RUF", # ruff
    "I", # isort
    "N", # pep8-naming
    "PL" # pylint
]
ignore = [
    "D203", # Incorrect blank line before class
    "D212", # Multi-line docstring summary should start at the first line
    "D404", # First word should not be "This"
    "N802", # Should be lower case, conflicts with tango
    "PLR0913", # Too many argument
    "PLR0912", # Too many branches
    "PLR0917", # Too many positional arguments
    "PLR2004", # should be annotated with `typing.ClassVar`
    "RUF012", # Mutable class attributes should be annotated with `typing.ClassVar
    "PT001", # fixture brackets
    "PLR0915", # Too many statements
    "PLC0415", # import should be at the top-level of a file
    "PLR5501", # Use elif
    "D401", # noun-phrase docstrings read better for builders like `label()`
    "PLR0911", # Too many return statements: dispatch functions
]
 
# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []
 
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
 
[format]
# Like Black, use double quotes for strings.
quote-style = "double"
 
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
 
# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false
 
# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
 
# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = true
 
# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = 70


[lint.per-file-ignores]
"tests/*" = ["D102", "D107", "PT018", "PLR2004", "S101"]
