########################################################################
# TARANTA
#
# Generated by ska-taranta-setup (`ska-taranta init`). Safe to edit; `init`
# won't overwrite it unless run with --force.
########################################################################

TARANTA_RUN ?= uv run
TARANTA_PORT ?= 8080
TARANTA_URL ?= http://localhost:$(TARANTA_PORT)/$(KUBE_NAMESPACE)/taranta/

# taranta-auth needs this secret to exist, even with local (non-Microsoft) login.
taranta-auth-secret: ## create the placeholder secret taranta-auth expects
	@echo "==> Creating placeholder taranta-auth-ms-client-secret in $(KUBE_NAMESPACE)..."
	kubectl create namespace $(KUBE_NAMESPACE) --dry-run=client -o yaml | kubectl apply -f -
	kubectl create secret generic taranta-auth-ms-client-secret \
		-n $(KUBE_NAMESPACE) \
		--from-literal=MS_CLIENT_SECRET=placeholder-not-used-by-local-auth \
		--dry-run=client -o yaml | kubectl apply -f -

# Make sure the secret exists before every chart install.
k8s-pre-install-chart: taranta-auth-secret

taranta-minikube-setup: ## expose Taranta on localhost:$(TARANTA_PORT) via the minikube ingress
	@echo "==> Enabling ingress addon..."
	minikube addons enable ingress
	@echo "==> Waiting for ingress controller to be ready..."
	kubectl wait --namespace ingress-nginx \
		--for=condition=ready pod \
		--selector=app.kubernetes.io/component=controller \
		--timeout=120s
	@echo "==> Starting minikube tunnel in background (may prompt for sudo)..."
	nohup minikube tunnel > /tmp/minikube-tunnel.log 2>&1 &
	@echo "==> Starting port-forward for ingress on localhost:$(TARANTA_PORT)..."
	nohup kubectl port-forward -n ingress-nginx svc/ingress-nginx-controller \
		$(TARANTA_PORT):80 --address 0.0.0.0 > /tmp/kubectl-port-forward.log 2>&1 &
	@echo ""
	@echo "==> Ready! Access Taranta at: $(TARANTA_URL)"
	@echo "    Tunnel log:       /tmp/minikube-tunnel.log"
	@echo "    Port-forward log: /tmp/kubectl-port-forward.log"

taranta-minikube-teardown: ## stop the Taranta port-forward and minikube tunnel
	@echo "==> Stopping port-forward..."
	-@lsof -ti tcp:$(TARANTA_PORT) | xargs -r kill -9
	@echo "==> Stopping minikube tunnel..."
	-@pkill -f "minikube tunnel" || true
	@echo "==> Disabling ingress addon..."
	minikube addons disable ingress
	@echo "==> Done!"

taranta-dashboards: ## discover devices and regenerate the Taranta dashboards
	$(TARANTA_RUN) ska-taranta discover
	$(TARANTA_RUN) ska-taranta generate

taranta-dashboards-live: ## regenerate dashboards from the devices running in $(KUBE_NAMESPACE)
	$(TARANTA_RUN) ska-taranta discover --live
	$(TARANTA_RUN) ska-taranta generate

taranta-upload: ## upload the generated dashboards to the running Taranta
	$(TARANTA_RUN) ska-taranta upload --url $(TARANTA_URL)

taranta-url: ## print the Taranta URL
	@echo $(TARANTA_URL)

.PHONY: taranta-auth-secret taranta-minikube-setup taranta-minikube-teardown \
	taranta-dashboards taranta-dashboards-live taranta-upload taranta-url
